/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

import com.google.protobuf.gradle.*

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `idea`
    id("com.google.protobuf") version "0.8.8"
}

group = "io.buttplug"
version = "0.0.1"

java {
    sourceCompatibility = org.gradle.api.JavaVersion.VERSION_1_8
    targetCompatibility = org.gradle.api.JavaVersion.VERSION_1_8
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

sourceSets {
    main {
        proto {
            srcDir("../../protobuf_schemas")
        }
    }
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // ffi
    implementation("net.java.dev.jna:jna:5.8.0")
    implementation("com.google.protobuf:protobuf-java:3.6.1")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.6.1"
    }
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
