// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Endpoint : ushort
{
  Tx = 0,
  Rx = 1,
  RxPressure = 2,
  RxTouch = 3,
  RxAccel = 4,
  Command = 5,
  Firmware = 6,
  TxMode = 7,
  TxVibrate = 8,
  TxShock = 9,
  TxVendorControl = 10,
  Whitelist = 11,
};

