// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct BatteryLevelCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static BatteryLevelCmd GetRootAsBatteryLevelCmd(ByteBuffer _bb) { return GetRootAsBatteryLevelCmd(_bb, new BatteryLevelCmd()); }
  public static BatteryLevelCmd GetRootAsBatteryLevelCmd(ByteBuffer _bb, BatteryLevelCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BatteryLevelCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartBatteryLevelCmd(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<ButtplugFFI.BatteryLevelCmd> EndBatteryLevelCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.BatteryLevelCmd>(o);
  }
};


}
