// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

public enum ButtplugErrorType : sbyte
{
  ButtplugConnectorError = 0,
  ButtplugHandshakeError = 1,
  ButtplugDeviceError = 2,
  ButtplugPingError = 3,
  ButtplugMessageError = 4,
  ButtplugUnknownError = 5,
};


}
