// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ClientConnected : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ClientConnected GetRootAsClientConnected(ByteBuffer _bb) { return GetRootAsClientConnected(_bb, new ClientConnected()); }
  public static ClientConnected GetRootAsClientConnected(ByteBuffer _bb, ClientConnected obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientConnected __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ClientId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<ButtplugFFI.ClientConnected> CreateClientConnected(FlatBufferBuilder builder,
      uint id = 0,
      uint client_id = 0) {
    builder.StartTable(2);
    ClientConnected.AddClientId(builder, client_id);
    ClientConnected.AddId(builder, id);
    return ClientConnected.EndClientConnected(builder);
  }

  public static void StartClientConnected(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddClientId(FlatBufferBuilder builder, uint clientId) { builder.AddUint(1, clientId, 0); }
  public static Offset<ButtplugFFI.ClientConnected> EndClientConnected(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.ClientConnected>(o);
  }
};


}
