// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

public enum ClientMessageType : byte
{
  NONE = 0,
  ConnectLocal = 1,
  ConnectWebsocket = 2,
  StartScanning = 3,
  StopScanning = 4,
  RequestDeviceList = 5,
};


}
