// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

public enum CreateClientType : byte
{
  NONE = 0,
  CreateLocal = 1,
  CreateWebsocket = 2,
};


}
