// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

public enum DeviceMessageType : byte
{
  NONE = 0,
  VibrateCmd = 1,
  RotateCmd = 2,
  LinearCmd = 3,
  StopDeviceCmd = 4,
  RawReadCmd = 5,
  RawWriteCmd = 6,
  RawSubscribeCmd = 7,
  RawUnsubscribeCmd = 8,
  BatteryLevelCmd = 9,
  RSSILevelCmd = 10,
};


}
