// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

[System.FlagsAttribute]
public enum DeviceCommunicationManagerTypes : ushort
{
  Btleplug = 1,
  XInput = 2,
  SerialPort = 4,
  LovenseHIDDongle = 8,
  LovenseSerialDongle = 16,
};


}
