// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DeviceEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DeviceEvent GetRootAsDeviceEvent(ByteBuffer _bb) { return GetRootAsDeviceEvent(_bb, new DeviceEvent()); }
  public static DeviceEvent GetRootAsDeviceEvent(ByteBuffer _bb, DeviceEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeviceEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ButtplugFFI.DeviceEventType EventType { get { int o = __p.__offset(6); return o != 0 ? (ButtplugFFI.DeviceEventType)__p.bb.Get(o + __p.bb_pos) : ButtplugFFI.DeviceEventType.NONE; } }
  public TTable? Event<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }

  public static Offset<ButtplugFFI.DeviceEvent> CreateDeviceEvent(FlatBufferBuilder builder,
      uint device_index = 0,
      ButtplugFFI.DeviceEventType event_type = ButtplugFFI.DeviceEventType.NONE,
      int eventOffset = 0) {
    builder.StartTable(3);
    DeviceEvent.AddEvent(builder, eventOffset);
    DeviceEvent.AddDeviceIndex(builder, device_index);
    DeviceEvent.AddEventType(builder, event_type);
    return DeviceEvent.EndDeviceEvent(builder);
  }

  public static void StartDeviceEvent(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddDeviceIndex(FlatBufferBuilder builder, uint deviceIndex) { builder.AddUint(0, deviceIndex, 0); }
  public static void AddEventType(FlatBufferBuilder builder, ButtplugFFI.DeviceEventType eventType) { builder.AddByte(1, (byte)eventType, 0); }
  public static void AddEvent(FlatBufferBuilder builder, int eventOffset) { builder.AddOffset(2, eventOffset, 0); }
  public static Offset<ButtplugFFI.DeviceEvent> EndDeviceEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.DeviceEvent>(o);
  }
  public static void FinishDeviceEventBuffer(FlatBufferBuilder builder, Offset<ButtplugFFI.DeviceEvent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDeviceEventBuffer(FlatBufferBuilder builder, Offset<ButtplugFFI.DeviceEvent> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
