// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

public enum DeviceEventType : byte
{
  NONE = 0,
  Disconnect = 1,
  BatteryLevelReading = 2,
  RSSILevelReading = 3,
};


}
