// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Error : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Error GetRootAsError(ByteBuffer _bb) { return GetRootAsError(_bb, new Error()); }
  public static Error GetRootAsError(ByteBuffer _bb, Error obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Error __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartError(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<ButtplugFFI.Error> EndError(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.Error>(o);
  }
};


}
