// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct GetDevice : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static GetDevice GetRootAsGetDevice(ByteBuffer _bb) { return GetRootAsGetDevice(_bb, new GetDevice()); }
  public static GetDevice GetRootAsGetDevice(ByteBuffer _bb, GetDevice obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetDevice __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<ButtplugFFI.GetDevice> CreateGetDevice(FlatBufferBuilder builder,
      uint device_id = 0) {
    builder.StartTable(1);
    GetDevice.AddDeviceId(builder, device_id);
    return GetDevice.EndGetDevice(builder);
  }

  public static void StartGetDevice(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static Offset<ButtplugFFI.GetDevice> EndGetDevice(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.GetDevice>(o);
  }
};


}
