// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LinearComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static LinearComponent GetRootAsLinearComponent(ByteBuffer _bb) { return GetRootAsLinearComponent(_bb, new LinearComponent()); }
  public static LinearComponent GetRootAsLinearComponent(ByteBuffer _bb, LinearComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LinearComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Index { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Duration { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public double Position { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<ButtplugFFI.LinearComponent> CreateLinearComponent(FlatBufferBuilder builder,
      uint index = 0,
      uint duration = 0,
      double position = 0.0) {
    builder.StartTable(3);
    LinearComponent.AddPosition(builder, position);
    LinearComponent.AddDuration(builder, duration);
    LinearComponent.AddIndex(builder, index);
    return LinearComponent.EndLinearComponent(builder);
  }

  public static void StartLinearComponent(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddIndex(FlatBufferBuilder builder, uint index) { builder.AddUint(0, index, 0); }
  public static void AddDuration(FlatBufferBuilder builder, uint duration) { builder.AddUint(1, duration, 0); }
  public static void AddPosition(FlatBufferBuilder builder, double position) { builder.AddDouble(2, position, 0.0); }
  public static Offset<ButtplugFFI.LinearComponent> EndLinearComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.LinearComponent>(o);
  }
};


}
