// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

public enum MessageAttributeType : ushort
{
  VibrateCmd = 0,
  RotateCmd = 1,
  LinearCmd = 2,
  StopDeviceCmd = 3,
  RawReadCmd = 4,
  RawWriteCmd = 5,
  RawSubscribeCmd = 6,
  RawUnsubscribeCmd = 7,
  BatteryLevelCmd = 8,
  RSSILevelCmd = 9,
};


}
