// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Ok : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Ok GetRootAsOk(ByteBuffer _bb) { return GetRootAsOk(_bb, new Ok()); }
  public static Ok GetRootAsOk(ByteBuffer _bb, Ok obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Ok __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartOk(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<ButtplugFFI.Ok> EndOk(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.Ok>(o);
  }
};


}
