// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RSSILevelCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static RSSILevelCmd GetRootAsRSSILevelCmd(ByteBuffer _bb) { return GetRootAsRSSILevelCmd(_bb, new RSSILevelCmd()); }
  public static RSSILevelCmd GetRootAsRSSILevelCmd(ByteBuffer _bb, RSSILevelCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RSSILevelCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRSSILevelCmd(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<ButtplugFFI.RSSILevelCmd> EndRSSILevelCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.RSSILevelCmd>(o);
  }
};


}
