// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

public enum ServerMessageType : byte
{
  NONE = 0,
  Ok = 1,
  Error = 2,
  ScanningFinished = 3,
  DeviceAdded = 4,
  DeviceRemoved = 5,
};


}
