// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct StartScanning : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static StartScanning GetRootAsStartScanning(ByteBuffer _bb) { return GetRootAsStartScanning(_bb, new StartScanning()); }
  public static StartScanning GetRootAsStartScanning(ByteBuffer _bb, StartScanning obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StartScanning __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartStartScanning(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<ButtplugFFI.StartScanning> EndStartScanning(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.StartScanning>(o);
  }
};


}
