// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct StopScanning : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static StopScanning GetRootAsStopScanning(ByteBuffer _bb) { return GetRootAsStopScanning(_bb, new StopScanning()); }
  public static StopScanning GetRootAsStopScanning(ByteBuffer _bb, StopScanning obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StopScanning __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartStopScanning(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<ButtplugFFI.StopScanning> EndStopScanning(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.StopScanning>(o);
  }
};


}
