// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ButtplugFFI
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct StopDeviceCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static StopDeviceCmd GetRootAsStopDeviceCmd(ByteBuffer _bb) { return GetRootAsStopDeviceCmd(_bb, new StopDeviceCmd()); }
  public static StopDeviceCmd GetRootAsStopDeviceCmd(ByteBuffer _bb, StopDeviceCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StopDeviceCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartStopDeviceCmd(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<ButtplugFFI.StopDeviceCmd> EndStopDeviceCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ButtplugFFI.StopDeviceCmd>(o);
  }
};


}
